#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\FileController::index
app_logout:
    path: /logout
    methods: GET

# JWT login check
login_check:
    path: /api/login_check
    methods: ['POST']